---
title: "Ideogram.js visualization"
author: "Boyu Yu"
date: "March 23, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Example copied from the origianl package

```{r, fig.height=13}
library(ideogRam)
ideogRam(
    data = list(
        organism = "human",
        orientation = "horizontal",
        annotations = list(
            list(
                name = "xxx",
                chr = "2",
                start = 34294,
                stop = 125482
            ),
            list(
                name = "BRCA1",
                chr = "17",
                start = 43125400,
                stop = 43125482
            )
        )
    )
)
```

## Example using GRanges

The following code produces the same result as above, but it accepts GRanges as input.

```{r, fig.height=13}
library(GenomicRanges)
gr <- GRanges(seqnames = c(2, 17),
              IRanges(start = c(34294, 43125400), end = c(125482, 43125482)))
gr

# This function converts GRanges to data frame for input
annotation_with_gr <- function(x) {
    df <- as.data.frame(x)
    df <- data.frame(chr = df$seqnames, start = df$start, stop = df$end)
    jsonlite::toJSON(df)
}

ideogRam(
    data = list(
        organism = "human",
        orientation = "horizontal",
        annotations = annotation_with_gr(gr)
    )
)
```

## Another example

```{r, fig.height=3}
gr <- GRanges("7", IRanges(start = c(199999, 6000000), end = c(3000000, 9000000)))
gr
ideogRam(list(
    organism = "human",
    chromosome = "7",
    orientation = "horizontal",
    annotations = annotation_with_gr(gr),
    annotationsLayout = "overlay"
))
```





